# Generated by Django 3.1.4 on 2020-12-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='topics',
            new_name='topic',
        ),
    ]
